# Generated by Django 4.0.1 on 2022-12-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, default='None', upload_to='media/'),
        ),
    ]
