# Generated by Django 4.0.1 on 2023-01-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listings_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
    ]
