# Generated by Django 4.0.1 on 2023-01-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listings_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='file',
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank='None', upload_to='images/'),
        ),
    ]
