# Generated by Django 4.0.1 on 2023-01-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listings_file_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.FileField(blank='None', upload_to='images/'),
        ),
    ]
